import random

# Generates a random number form 0 to 100
def randomize():
    rand_num = random.randrange(0, 100)
    return rand_num

#  Splits entered or generated by the randomize function two-digit  number in tens and ones and prints them out 
def split_num(input_num = False):
    print(type(input_num))
    if input_num:
        tens = (input_num// 10)
        ones = (input_num % 10)
        print(str(tens) + str(ones))
        print("The number you have entered has {} tens and {} ones.".format(str(tens), str(ones)))
    else:
        get_num = randomize()
        tens = (get_num//10)
        ones = (get_num%10)
        print(str(tens)+str(ones))
        print("The generated number has {} tens and {} ones.".format(str(tens), str(ones)))
split_num()
